apiVersion: v1
kind: Service
metadata:
  name: flexlance-service
spec:
  selector:
    app: flexlance-app
  ports:
    - name: backend
      port: 8080
      targetPort: 8080
    - name: frontend
      port: 3000
      targetPort: 3000
  type: ClusterIP

